const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const crypto = require('crypto');
const supabase = require('../config/supabase');
const { decrypt } = require('./encryption');

async function createPDF(caseId, institution = 'Beneficiary Bank') {
  // 1. Fetch Case Data
  const { data: caseData, error: caseError } = await supabase
    .from('cases')
    .select('*')
    .eq('id', caseId)
    .single();

  if (caseError) throw caseError;

  const payload = caseData.payload || {};
  const utr = decrypt(payload.utr);
  const vpa = decrypt(payload.beneficiary_vpa);

  // 2. Generate PDF using pdf-lib
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([600, 800]);
  const { width, height } = page.getSize();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Watermark
  page.drawText('FRAUDSHIELD OFFICIAL', {
    x: 150, y: 400, size: 40, font: boldFont,
    color: rgb(0.9, 0.9, 0.9), opacity: 0.2, rotate: { type: 'degrees', angle: 45 }
  });

  page.drawText('LEGAL LIEN MARKING REQUEST', { x: 50, y: height - 50, size: 18, font: boldFont, color: rgb(0, 0.1, 0.4) });
  page.drawText(`Date: ${new Date().toLocaleString()}`, { x: 50, y: height - 80, size: 10, font });
  page.drawText(`Case ID: ${caseId}`, { x: 50, y: height - 95, size: 10, font });

  const content = [
    `To: The Nodal Officer, ${institution}`,
    `Subject: Urgent Lien Marking Request for Fraudulent Transaction`,
    ``,
    `As per RBI Circular RBI/2021-22/75 on Customer Protection, we hereby report a`,
    `confirmed fraudulent transaction and request immediate lien marking on the`,
    `following beneficiary account:`,
    ``,
    `Beneficiary VPA/Account: ${vpa}`,
    `Transaction UTR: ${utr}`,
    `Amount: INR ${caseData.amount.toLocaleString('en-IN')}`,
    `Incident Timestamp: ${caseData.created_at}`,
    ``,
    `The transaction has been analyzed by the FraudShield FIU system and flagged`,
    `with a high risk score. Under the 'Golden Hour' protocol, we request you to`,
    `freeze/lien the specified amount immediately to prevent further siphoning.`,
    ``,
    `This is an automated request generated by the FraudShield Intelligence Center.`,
    `Please acknowledge receipt of this request immediately via return email.`
  ];

  let yOffset = height - 150;
  content.forEach(line => {
    page.drawText(line, { x: 50, y: yOffset, size: 11, font: line.startsWith('Beneficiary') || line.startsWith('Transaction') ? boldFont : font });
    yOffset -= 18;
  });

  const tempPdfBytes = await pdfDoc.save();
  const hash = crypto.createHash('sha256').update(tempPdfBytes).digest('hex');
  page.drawText(`Document Integrity Hash: ${hash}`, { x: 50, y: 50, size: 8, font });
  
  return { 
    pdfBytes: await pdfDoc.save(), 
    hash, 
    caseData 
  };
}

module.exports = { createPDF };
